/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

/**
 *
 * @author SUPORTE-TI
 */
public class CadProdutos extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public CadProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos"); // mudar o nome da janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarProdutos = new javax.swing.JPanel();
        cadLabelIdProd = new javax.swing.JLabel();
        cadTxtIdProd = new javax.swing.JTextField();
        cadLabelNomeProd = new javax.swing.JLabel();
        cadTxtNomeProd = new javax.swing.JTextField();
        cadBtnCadastrarProd = new javax.swing.JButton();
        cadLabelQuantProd = new javax.swing.JLabel();
        cadTxtQuantProd = new javax.swing.JTextField();
        LabelCadProd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastrarProdutos.setName(""); // NOI18N

        cadLabelIdProd.setText("IdProduto");

        cadTxtIdProd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cadTxtIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTxtIdProdActionPerformed(evt);
            }
        });

        cadLabelNomeProd.setText("Nome");

        cadTxtNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTxtNomeProdActionPerformed(evt);
            }
        });

        cadBtnCadastrarProd.setText("Cadastrar");
        cadBtnCadastrarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadLabelQuantProd.setText("Quantidade");

        LabelCadProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelCadProd.setText("Cadastro de Produtos");

        javax.swing.GroupLayout CadastrarProdutosLayout = new javax.swing.GroupLayout(CadastrarProdutos);
        CadastrarProdutos.setLayout(CadastrarProdutosLayout);
        CadastrarProdutosLayout.setHorizontalGroup(
            CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                                .addComponent(cadLabelIdProd)
                                .addGap(27, 27, 27)
                                .addComponent(cadTxtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadLabelQuantProd)
                                    .addComponent(cadLabelNomeProd))
                                .addGap(18, 18, 18)
                                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadTxtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadTxtQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(cadBtnCadastrarProd))
                    .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelCadProd)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        CadastrarProdutosLayout.setVerticalGroup(
            CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadLabelIdProd)
                    .addComponent(cadTxtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadLabelNomeProd)
                    .addComponent(cadTxtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadLabelQuantProd)
                    .addComponent(cadTxtQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cadBtnCadastrarProd)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastrarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CadastrarProdutos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadTxtIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTxtIdProdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cadTxtIdProdActionPerformed

    private void cadTxtNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTxtNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadTxtNomeProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadProdutos dialog = new CadProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastrarProdutos;
    private javax.swing.JLabel LabelCadProd;
    private javax.swing.JButton cadBtnCadastrarProd;
    private javax.swing.JLabel cadLabelIdProd;
    private javax.swing.JLabel cadLabelNomeProd;
    private javax.swing.JLabel cadLabelQuantProd;
    private javax.swing.JTextField cadTxtIdProd;
    private javax.swing.JTextField cadTxtNomeProd;
    private javax.swing.JTextField cadTxtQuantProd;
    // End of variables declaration//GEN-END:variables
}
