/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author SUPORTE-TI
 */
public class main extends javax.swing.JFrame {
    public main() {
        initComponents();
        setTitle("Tela Principal"); //nome da tela
        setLocationRelativeTo(null); //inicia a tela no centro
        setResizable(false); // travar redimensionamento
        setSize(800, 600); // trava o tamanho
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelIdVenda = new javax.swing.JLabel();
        txtIdVenda = new javax.swing.JTextField();
        labelComprador = new javax.swing.JLabel();
        txtComprador = new javax.swing.JTextField();
        boxItem = new javax.swing.JComboBox<>();
        SpinnerQuant = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        scrollPnl = new javax.swing.JScrollPane();
        tabelaBolsa = new javax.swing.JTable();
        btnEnviar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlConsultas = new javax.swing.JPanel();
        tabsConsultas = new javax.swing.JTabbedPane();
        pnlVendas = new javax.swing.JPanel();
        scrollVendas = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();
        pnlProdutos = new javax.swing.JPanel();
        scrollProdutos = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        pnlClientes = new javax.swing.JPanel();
        scrollClientes = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        pnlUsuarios = new javax.swing.JPanel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        mnVendas = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenu();
        mnCadastrarClientes = new javax.swing.JMenuItem();
        mnCadastrarProdutos = new javax.swing.JMenuItem();
        mnCadastrarUsuarios = new javax.swing.JMenuItem();
        mnBackup = new javax.swing.JMenu();
        Backup = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnVisualizarClientes = new javax.swing.JMenuItem();
        mnVisualizarProdutos = new javax.swing.JMenuItem();
        mnHistorico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        labelIdVenda.setText("Número de venda:");

        txtIdVenda.setEnabled(false);
        txtIdVenda.setMaximumSize(new java.awt.Dimension(64, 25));
        txtIdVenda.setMinimumSize(new java.awt.Dimension(64, 25));
        txtIdVenda.setPreferredSize(null);

        labelComprador.setText("Comprador");

        txtComprador.setMaximumSize(new java.awt.Dimension(70, 30));
        txtComprador.setMinimumSize(new java.awt.Dimension(70, 30));
        txtComprador.setPreferredSize(new java.awt.Dimension(130, 30));

        boxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxItem.setMaximumSize(new java.awt.Dimension(70, 30));
        boxItem.setMinimumSize(new java.awt.Dimension(70, 30));
        boxItem.setPreferredSize(new java.awt.Dimension(70, 30));
        boxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxItemActionPerformed(evt);
            }
        });

        SpinnerQuant.setMaximumSize(new java.awt.Dimension(65, 30));
        SpinnerQuant.setMinimumSize(new java.awt.Dimension(65, 30));
        SpinnerQuant.setPreferredSize(new java.awt.Dimension(65, 30));

        btnAdd.setText("Adicionar");
        btnAdd.setMaximumSize(new java.awt.Dimension(97, 32));
        btnAdd.setMinimumSize(new java.awt.Dimension(97, 32));
        btnAdd.setPreferredSize(new java.awt.Dimension(97, 32));

        tabelaBolsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaBolsa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tabelaBolsa.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaBolsa.setInheritsPopupMenu(true);
        scrollPnl.setViewportView(tabelaBolsa);

        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.setMaximumSize(new java.awt.Dimension(97, 32));
        btnEnviar.setMinimumSize(new java.awt.Dimension(97, 32));
        btnEnviar.setPreferredSize(new java.awt.Dimension(97, 32));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setMaximumSize(new java.awt.Dimension(97, 32));
        btnAlterar.setMinimumSize(new java.awt.Dimension(97, 32));
        btnAlterar.setPreferredSize(new java.awt.Dimension(97, 32));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setMaximumSize(new java.awt.Dimension(70, 30));
        btnExcluir.setMinimumSize(new java.awt.Dimension(70, 30));
        btnExcluir.setPreferredSize(new java.awt.Dimension(70, 30));

        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelIdVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelComprador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdVenda)
                    .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComprador)
                    .addComponent(boxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
        );

        tbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollVendas.setViewportView(tbVendas);

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVendasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVendasLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(scrollVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabsConsultas.addTab("Vendas ", pnlVendas);

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Quantidade", "Preço"
            }
        ));
        scrollProdutos.setViewportView(tbProdutos);

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(scrollProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabsConsultas.addTab("Produtos", pnlProdutos);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollClientes.setViewportView(tbClientes);

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabsConsultas.addTab("Clientes", pnlClientes);

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollUsuarios.setViewportView(tbUsuarios);

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabsConsultas.addTab("Usuários", pnlUsuarios);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsConsultas)
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsConsultas)
        );

        menuBar.setMinimumSize(new java.awt.Dimension(253, 40));
        menuBar.setPreferredSize(new java.awt.Dimension(253, 40));

        mnVendas.setText("Principal");
        mnVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.add(mnVendas);

        mnClientes.setText("Cadastros");

        mnCadastrarClientes.setText("Cadastrar Clientes");
        mnCadastrarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarClientesActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarClientes);

        mnCadastrarProdutos.setText("Cadastrar Produtos");
        mnCadastrarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarProdutosActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarProdutos);

        mnCadastrarUsuarios.setText("Cadastrar Usuários");
        mnCadastrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarUsuariosActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarUsuarios);

        menuBar.add(mnClientes);

        mnBackup.setText("Backup");

        Backup.setText("Backup");
        mnBackup.add(Backup);

        menuBar.add(mnBackup);

        mnConsultas.setText("Consultas");

        mnVisualizarClientes.setText("Visualizar Clientes");
        mnVisualizarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnVisualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarClientesActionPerformed(evt);
            }
        });
        mnConsultas.add(mnVisualizarClientes);

        mnVisualizarProdutos.setText("Visualizar Produtos");
        mnVisualizarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnVisualizarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarProdutosActionPerformed(evt);
            }
        });
        mnConsultas.add(mnVisualizarProdutos);

        mnHistorico.setText("Historico de Vendas");
        mnHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.add(mnHistorico);

        menuBar.add(mnConsultas);

        jMenu1.setText("Consultas");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarClientesActionPerformed
        // TODO add your handling code here:
        CadClientes dialog = new CadClientes (this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnCadastrarClientesActionPerformed

    private void mnCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarProdutosActionPerformed
            // TODO add your handling code here:
            
            CadProdutos dialog = new CadProdutos(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
           
            
    }//GEN-LAST:event_mnCadastrarProdutosActionPerformed

    private void mnCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarUsuariosActionPerformed
        // TODO add your handling code here:
        CadUsuarios dialog = new CadUsuarios(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnCadastrarUsuariosActionPerformed

    private void boxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxItemActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void mnVisualizarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarProdutosActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_mnVisualizarProdutosActionPerformed

    private void mnVisualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnVisualizarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Backup;
    private javax.swing.JSpinner SpinnerQuant;
    private javax.swing.JComboBox<String> boxItem;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel labelComprador;
    private javax.swing.JLabel labelIdVenda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnBackup;
    private javax.swing.JMenuItem mnCadastrarClientes;
    private javax.swing.JMenuItem mnCadastrarProdutos;
    private javax.swing.JMenuItem mnCadastrarUsuarios;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mnHistorico;
    private javax.swing.JMenu mnVendas;
    private javax.swing.JMenuItem mnVisualizarClientes;
    private javax.swing.JMenuItem mnVisualizarProdutos;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JPanel pnlVendas;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JScrollPane scrollPnl;
    private javax.swing.JScrollPane scrollProdutos;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JScrollPane scrollVendas;
    private javax.swing.JTable tabelaBolsa;
    private javax.swing.JTabbedPane tabsConsultas;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTable tbVendas;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtIdVenda;
    // End of variables declaration//GEN-END:variables
}
