/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author SUPORTE-TI
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setTitle("Tela Principal"); //nome da tela
        setLocationRelativeTo(null); //inicia a tela no centro
        setResizable(false); // travar redimensionamento
        setSize(800, 600); // trava o tamanho
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        labelIdVenda = new javax.swing.JLabel();
        txtIdVenda = new javax.swing.JTextField();
        labelComprador = new javax.swing.JLabel();
        txtComprador = new javax.swing.JTextField();
        boxItem = new javax.swing.JComboBox<>();
        SpinnerQuant = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        scrollPnl = new javax.swing.JScrollPane();
        tabelaBolsa = new javax.swing.JTable();
        btnEnviar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnVendas = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenu();
        mnCadastrarClientes = new javax.swing.JMenuItem();
        mnCadastrarProdutos = new javax.swing.JMenuItem();
        mnCadastrarUsuarios = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenu();
        mnVisualizarClientes = new javax.swing.JMenuItem();
        mnVisualizarProdutos = new javax.swing.JMenuItem();
        mnHistorico = new javax.swing.JMenuItem();
        mnBackup = new javax.swing.JMenu();
        Backup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        labelIdVenda.setText("Número de venda:");

        txtIdVenda.setEnabled(false);
        txtIdVenda.setMaximumSize(new java.awt.Dimension(64, 25));
        txtIdVenda.setMinimumSize(new java.awt.Dimension(64, 25));
        txtIdVenda.setPreferredSize(null);

        labelComprador.setText("Comprador");

        txtComprador.setMaximumSize(new java.awt.Dimension(70, 30));
        txtComprador.setMinimumSize(new java.awt.Dimension(70, 30));
        txtComprador.setPreferredSize(new java.awt.Dimension(130, 30));

        boxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxItem.setMaximumSize(new java.awt.Dimension(70, 30));
        boxItem.setMinimumSize(new java.awt.Dimension(70, 30));
        boxItem.setPreferredSize(new java.awt.Dimension(70, 30));
        boxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxItemActionPerformed(evt);
            }
        });

        SpinnerQuant.setMaximumSize(new java.awt.Dimension(65, 30));
        SpinnerQuant.setMinimumSize(new java.awt.Dimension(65, 30));
        SpinnerQuant.setPreferredSize(new java.awt.Dimension(65, 30));

        btnAdd.setText("Adicionar");

        tabelaBolsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPnl.setViewportView(tabelaBolsa);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setMaximumSize(new java.awt.Dimension(70, 30));
        btnAlterar.setMinimumSize(new java.awt.Dimension(70, 30));
        btnAlterar.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(70, 30));
        btnExcluir.setMinimumSize(new java.awt.Dimension(70, 30));
        btnExcluir.setPreferredSize(new java.awt.Dimension(70, 30));

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelIdVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(labelComprador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdVenda)
                    .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComprador)
                    .addComponent(boxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241))
        );

        menuBar.setPreferredSize(new java.awt.Dimension(253, 25));

        mnVendas.setText("Principal");
        mnVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.add(mnVendas);

        mnClientes.setText("Cadastros");

        mnCadastrarClientes.setText("Cadastrar Clientes");
        mnCadastrarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarClientesActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarClientes);

        mnCadastrarProdutos.setText("Cadastrar Produtos");
        mnCadastrarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarProdutosActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarProdutos);

        mnCadastrarUsuarios.setText("Cadastrar Usuários");
        mnCadastrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarUsuariosActionPerformed(evt);
            }
        });
        mnClientes.add(mnCadastrarUsuarios);

        menuBar.add(mnClientes);

        mnProdutos.setText("Consultas");

        mnVisualizarClientes.setText("Visualizar Clientes");
        mnVisualizarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnProdutos.add(mnVisualizarClientes);

        mnVisualizarProdutos.setText("Visualizar Produtos");
        mnVisualizarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnProdutos.add(mnVisualizarProdutos);

        mnHistorico.setText("Historico de Vendas");
        mnHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnProdutos.add(mnHistorico);

        menuBar.add(mnProdutos);

        mnBackup.setText("Backup");

        Backup.setText("Backup");
        mnBackup.add(Backup);

        menuBar.add(mnBackup);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarClientesActionPerformed
        // TODO add your handling code here:
        CadClientes dialog = new CadClientes (this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnCadastrarClientesActionPerformed

    private void mnCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarProdutosActionPerformed
            // TODO add your handling code here:
            
            CadProdutos dialog = new CadProdutos(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
           
            
    }//GEN-LAST:event_mnCadastrarProdutosActionPerformed

    private void mnCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarUsuariosActionPerformed
        // TODO add your handling code here:
        CadUsuarios dialog = new CadUsuarios(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_mnCadastrarUsuariosActionPerformed

    private void boxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxItemActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Backup;
    private javax.swing.JSpinner SpinnerQuant;
    private javax.swing.JComboBox<String> boxItem;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel labelComprador;
    private javax.swing.JLabel labelIdVenda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnBackup;
    private javax.swing.JMenuItem mnCadastrarClientes;
    private javax.swing.JMenuItem mnCadastrarProdutos;
    private javax.swing.JMenuItem mnCadastrarUsuarios;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenuItem mnHistorico;
    private javax.swing.JMenu mnProdutos;
    private javax.swing.JMenu mnVendas;
    private javax.swing.JMenuItem mnVisualizarClientes;
    private javax.swing.JMenuItem mnVisualizarProdutos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane scrollPnl;
    private javax.swing.JTable tabelaBolsa;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtIdVenda;
    // End of variables declaration//GEN-END:variables
}
